name: Build linux

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
        
    steps:
    
    - name: install Qt5
      uses: jurplel/install-qt-action@v4
      with:
        #aqtversion: null # use whatever the default is
        dir: '${{ github.workspace }}/qt5'
        version: "5.15.2" 
        cache: true
        
    - name: install Qt6
      uses: jurplel/install-qt-action@v4
      with:
        #aqtversion: null # use whatever the default is
        modules: qtshadertools qtscxml
        dir: '${{ github.workspace }}/qt6'
        version: "6.7.3" 
        cache: true

    
    - name: Fetch Gammaray sources
      uses: actions/checkout@v4
      with:
        path: ./src
        submodules: recursive
        
    - name: Install Dependencies on Linux
      run: |
        sudo apt update -qq
        sudo apt install -y gdb doxygen

    
    - name: Install ninja-build tool (must be after Qt due PATH changes)
      uses: turtlesec-no/get-ninja@main

    - name: Build GammaRay
      run: |
        mkdir build && cd build/
        cmake -G Ninja -DCMAKE_INSTALL_PREFIX='${{ github.workspace }}/install' -DCMAKE_PREFIX_PATH=${{ github.workspace }}/qt6/gcc_64 ../src/
        cmake --build .
        cmake --build . --target install 
        
    - name: Build probe
      run: |
        cmake \
        -DCMAKE_BUILD_TYPE=Release \
        -DCMAKE_PREFIX_PATH=${{ github.workspace }}/qt5/gcc_64 \
        -DGAMMARAY_PROBE_ONLY_BUILD=true \
        -DGAMMARAY_BUILD_UI=false  \
        -DCMAKE_INSTALL_PREFIX=${{ github.workspace }}/install \
        ${{ github.workspace }}/src/
    
    - name: Zip-Release4cpp
      uses: darshitsri/zip-release@v3
      with:
        filename: Gammaray3.2.zip
        path: ${{ github.workspace }}/install/
    
   

     
